// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: payment/v1/payment.proto

package paymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreateCardCharge_FullMethodName   = "/payment.v1.PaymentService/CreateCardCharge"
	PaymentService_CreateSourceCharge_FullMethodName = "/payment.v1.PaymentService/CreateSourceCharge"
	PaymentService_GetCharge_FullMethodName          = "/payment.v1.PaymentService/GetCharge"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreateCardCharge(ctx context.Context, in *CreateCardChargeRequest, opts ...grpc.CallOption) (*CreateCardChargeResponse, error)
	CreateSourceCharge(ctx context.Context, in *CreateSourceChargeRequest, opts ...grpc.CallOption) (*CreateSourceChargeResponse, error)
	GetCharge(ctx context.Context, in *GetChargeRequest, opts ...grpc.CallOption) (*GetChargeResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateCardCharge(ctx context.Context, in *CreateCardChargeRequest, opts ...grpc.CallOption) (*CreateCardChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCardChargeResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreateCardCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateSourceCharge(ctx context.Context, in *CreateSourceChargeRequest, opts ...grpc.CallOption) (*CreateSourceChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSourceChargeResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreateSourceCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetCharge(ctx context.Context, in *GetChargeRequest, opts ...grpc.CallOption) (*GetChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChargeResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	CreateCardCharge(context.Context, *CreateCardChargeRequest) (*CreateCardChargeResponse, error)
	CreateSourceCharge(context.Context, *CreateSourceChargeRequest) (*CreateSourceChargeResponse, error)
	GetCharge(context.Context, *GetChargeRequest) (*GetChargeResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreateCardCharge(context.Context, *CreateCardChargeRequest) (*CreateCardChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCardCharge not implemented")
}
func (UnimplementedPaymentServiceServer) CreateSourceCharge(context.Context, *CreateSourceChargeRequest) (*CreateSourceChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSourceCharge not implemented")
}
func (UnimplementedPaymentServiceServer) GetCharge(context.Context, *GetChargeRequest) (*GetChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCharge not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateCardCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateCardCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateCardCharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateCardCharge(ctx, req.(*CreateCardChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateSourceCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSourceChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateSourceCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateSourceCharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateSourceCharge(ctx, req.(*CreateSourceChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetCharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetCharge(ctx, req.(*GetChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCardCharge",
			Handler:    _PaymentService_CreateCardCharge_Handler,
		},
		{
			MethodName: "CreateSourceCharge",
			Handler:    _PaymentService_CreateSourceCharge_Handler,
		},
		{
			MethodName: "GetCharge",
			Handler:    _PaymentService_GetCharge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
