// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCardChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CardToken     string                 `protobuf:"bytes,4,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardChargeRequest) Reset() {
	*x = CreateCardChargeRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardChargeRequest) ProtoMessage() {}

func (x *CreateCardChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardChargeRequest.ProtoReflect.Descriptor instead.
func (*CreateCardChargeRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardChargeRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateCardChargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateCardChargeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateCardChargeRequest) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

type CreateCardChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargeId      string                 `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AuthorizeUri  string                 `protobuf:"bytes,3,opt,name=authorize_uri,json=authorizeUri,proto3" json:"authorize_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardChargeResponse) Reset() {
	*x = CreateCardChargeResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardChargeResponse) ProtoMessage() {}

func (x *CreateCardChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardChargeResponse.ProtoReflect.Descriptor instead.
func (*CreateCardChargeResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardChargeResponse) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *CreateCardChargeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCardChargeResponse) GetAuthorizeUri() string {
	if x != nil {
		return x.AuthorizeUri
	}
	return ""
}

type CreateSourceChargeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	BookingId string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount    int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency  string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	SourceId  string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`    // เส้นทางเดิม (ถ้ามี)
	ReturnUri string                 `protobuf:"bytes,5,opt,name=return_uri,json=returnUri,proto3" json:"return_uri,omitempty"` // สำหรับช่องทางต้อง redirect (จากฝั่ง client เมื่อสร้าง source เอง)
	// NEW: ให้ server สร้าง source ให้ถ้า client ไม่ส่ง source_id
	SourceType    string `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // เช่น "promptpay", "internet_banking_kbank"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSourceChargeRequest) Reset() {
	*x = CreateSourceChargeRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSourceChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceChargeRequest) ProtoMessage() {}

func (x *CreateSourceChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceChargeRequest.ProtoReflect.Descriptor instead.
func (*CreateSourceChargeRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSourceChargeRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateSourceChargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateSourceChargeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSourceChargeRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateSourceChargeRequest) GetReturnUri() string {
	if x != nil {
		return x.ReturnUri
	}
	return ""
}

func (x *CreateSourceChargeRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type CreateSourceChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargeId      string                 `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	AuthorizeUri  string                 `protobuf:"bytes,2,opt,name=authorize_uri,json=authorizeUri,proto3" json:"authorize_uri,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSourceChargeResponse) Reset() {
	*x = CreateSourceChargeResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSourceChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceChargeResponse) ProtoMessage() {}

func (x *CreateSourceChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceChargeResponse.ProtoReflect.Descriptor instead.
func (*CreateSourceChargeResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSourceChargeResponse) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *CreateSourceChargeResponse) GetAuthorizeUri() string {
	if x != nil {
		return x.AuthorizeUri
	}
	return ""
}

func (x *CreateSourceChargeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargeId      string                 `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChargeRequest) Reset() {
	*x = GetChargeRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargeRequest) ProtoMessage() {}

func (x *GetChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargeRequest.ProtoReflect.Descriptor instead.
func (*GetChargeRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetChargeRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

type GetChargeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChargeId       string                 `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FailureCode    string                 `protobuf:"bytes,3,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage string                 `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChargeResponse) Reset() {
	*x = GetChargeResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargeResponse) ProtoMessage() {}

func (x *GetChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargeResponse.ProtoReflect.Descriptor instead.
func (*GetChargeResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetChargeResponse) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *GetChargeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetChargeResponse) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *GetChargeResponse) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"\x8b\x01\n" +
	"\x17CreateCardChargeRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"card_token\x18\x04 \x01(\tR\tcardToken\"t\n" +
	"\x18CreateCardChargeResponse\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rauthorize_uri\x18\x03 \x01(\tR\fauthorizeUri\"\xcb\x01\n" +
	"\x19CreateSourceChargeRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"return_uri\x18\x05 \x01(\tR\treturnUri\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\"v\n" +
	"\x1aCreateSourceChargeResponse\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId\x12#\n" +
	"\rauthorize_uri\x18\x02 \x01(\tR\fauthorizeUri\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"/\n" +
	"\x10GetChargeRequest\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId\"\x94\x01\n" +
	"\x11GetChargeResponse\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\ffailure_code\x18\x03 \x01(\tR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\x04 \x01(\tR\x0efailureMessage2\x9e\x02\n" +
	"\x0ePaymentService\x12]\n" +
	"\x10CreateCardCharge\x12#.payment.v1.CreateCardChargeRequest\x1a$.payment.v1.CreateCardChargeResponse\x12c\n" +
	"\x12CreateSourceCharge\x12%.payment.v1.CreateSourceChargeRequest\x1a&.payment.v1.CreateSourceChargeResponse\x12H\n" +
	"\tGetCharge\x12\x1c.payment.v1.GetChargeRequest\x1a\x1d.payment.v1.GetChargeResponseB=Z;github.com/you/badminton-booking/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_v1_payment_proto_goTypes = []any{
	(*CreateCardChargeRequest)(nil),    // 0: payment.v1.CreateCardChargeRequest
	(*CreateCardChargeResponse)(nil),   // 1: payment.v1.CreateCardChargeResponse
	(*CreateSourceChargeRequest)(nil),  // 2: payment.v1.CreateSourceChargeRequest
	(*CreateSourceChargeResponse)(nil), // 3: payment.v1.CreateSourceChargeResponse
	(*GetChargeRequest)(nil),           // 4: payment.v1.GetChargeRequest
	(*GetChargeResponse)(nil),          // 5: payment.v1.GetChargeResponse
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentService.CreateCardCharge:input_type -> payment.v1.CreateCardChargeRequest
	2, // 1: payment.v1.PaymentService.CreateSourceCharge:input_type -> payment.v1.CreateSourceChargeRequest
	4, // 2: payment.v1.PaymentService.GetCharge:input_type -> payment.v1.GetChargeRequest
	1, // 3: payment.v1.PaymentService.CreateCardCharge:output_type -> payment.v1.CreateCardChargeResponse
	3, // 4: payment.v1.PaymentService.CreateSourceCharge:output_type -> payment.v1.CreateSourceChargeResponse
	5, // 5: payment.v1.PaymentService.GetCharge:output_type -> payment.v1.GetChargeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
