// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: court/v1/court.proto

package courtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Court struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Venue         string                 `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"` //court name
	CourtNo       int32                  `protobuf:"varint,3,opt,name=court_no,json=courtNo,proto3" json:"court_no,omitempty"`
	PricePerHour  int64                  `protobuf:"varint,4,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	OpenFrom      string                 `protobuf:"bytes,5,opt,name=open_from,json=openFrom,proto3" json:"open_from,omitempty"`
	OpenTo        string                 `protobuf:"bytes,6,opt,name=open_to,json=openTo,proto3" json:"open_to,omitempty"`
	OwnerId       string                 `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // onwer court
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Court) Reset() {
	*x = Court{}
	mi := &file_court_v1_court_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Court) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Court) ProtoMessage() {}

func (x *Court) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Court.ProtoReflect.Descriptor instead.
func (*Court) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{0}
}

func (x *Court) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Court) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *Court) GetCourtNo() int32 {
	if x != nil {
		return x.CourtNo
	}
	return 0
}

func (x *Court) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *Court) GetOpenFrom() string {
	if x != nil {
		return x.OpenFrom
	}
	return ""
}

func (x *Court) GetOpenTo() string {
	if x != nil {
		return x.OpenTo
	}
	return ""
}

func (x *Court) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venue         string                 `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	CourtNo       int32                  `protobuf:"varint,2,opt,name=court_no,json=courtNo,proto3" json:"court_no,omitempty"`
	PricePerHour  int64                  `protobuf:"varint,3,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	OpenFrom      string                 `protobuf:"bytes,4,opt,name=open_from,json=openFrom,proto3" json:"open_from,omitempty"`
	OpenTo        string                 `protobuf:"bytes,5,opt,name=open_to,json=openTo,proto3" json:"open_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourtRequest) Reset() {
	*x = CreateCourtRequest{}
	mi := &file_court_v1_court_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourtRequest) ProtoMessage() {}

func (x *CreateCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourtRequest.ProtoReflect.Descriptor instead.
func (*CreateCourtRequest) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourtRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *CreateCourtRequest) GetCourtNo() int32 {
	if x != nil {
		return x.CourtNo
	}
	return 0
}

func (x *CreateCourtRequest) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *CreateCourtRequest) GetOpenFrom() string {
	if x != nil {
		return x.OpenFrom
	}
	return ""
}

func (x *CreateCourtRequest) GetOpenTo() string {
	if x != nil {
		return x.OpenTo
	}
	return ""
}

type CreateCourtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Court         *Court                 `protobuf:"bytes,1,opt,name=court,proto3" json:"court,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourtResponse) Reset() {
	*x = CreateCourtResponse{}
	mi := &file_court_v1_court_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourtResponse) ProtoMessage() {}

func (x *CreateCourtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourtResponse.ProtoReflect.Descriptor instead.
func (*CreateCourtResponse) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourtResponse) GetCourt() *Court {
	if x != nil {
		return x.Court
	}
	return nil
}

type GetCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourtRequest) Reset() {
	*x = GetCourtRequest{}
	mi := &file_court_v1_court_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourtRequest) ProtoMessage() {}

func (x *GetCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourtRequest.ProtoReflect.Descriptor instead.
func (*GetCourtRequest) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourtRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Court         *Court                 `protobuf:"bytes,1,opt,name=court,proto3" json:"court,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourtResponse) Reset() {
	*x = GetCourtResponse{}
	mi := &file_court_v1_court_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourtResponse) ProtoMessage() {}

func (x *GetCourtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourtResponse.ProtoReflect.Descriptor instead.
func (*GetCourtResponse) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourtResponse) GetCourt() *Court {
	if x != nil {
		return x.Court
	}
	return nil
}

type ListCourtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	VenueQuery    string                 `protobuf:"bytes,3,opt,name=venue_query,json=venueQuery,proto3" json:"venue_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourtsRequest) Reset() {
	*x = ListCourtsRequest{}
	mi := &file_court_v1_court_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourtsRequest) ProtoMessage() {}

func (x *ListCourtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourtsRequest.ProtoReflect.Descriptor instead.
func (*ListCourtsRequest) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{5}
}

func (x *ListCourtsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCourtsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCourtsRequest) GetVenueQuery() string {
	if x != nil {
		return x.VenueQuery
	}
	return ""
}

type ListCourtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courts        []*Court               `protobuf:"bytes,1,rep,name=courts,proto3" json:"courts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourtsResponse) Reset() {
	*x = ListCourtsResponse{}
	mi := &file_court_v1_court_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourtsResponse) ProtoMessage() {}

func (x *ListCourtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourtsResponse.ProtoReflect.Descriptor instead.
func (*ListCourtsResponse) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{6}
}

func (x *ListCourtsResponse) GetCourts() []*Court {
	if x != nil {
		return x.Courts
	}
	return nil
}

type UpdateCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Venue         string                 `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	CourtNo       int32                  `protobuf:"varint,3,opt,name=court_no,json=courtNo,proto3" json:"court_no,omitempty"`
	PricePerHour  int64                  `protobuf:"varint,4,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	OpenFrom      string                 `protobuf:"bytes,5,opt,name=open_from,json=openFrom,proto3" json:"open_from,omitempty"`
	OpenTo        string                 `protobuf:"bytes,6,opt,name=open_to,json=openTo,proto3" json:"open_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourtRequest) Reset() {
	*x = UpdateCourtRequest{}
	mi := &file_court_v1_court_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourtRequest) ProtoMessage() {}

func (x *UpdateCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourtRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourtRequest) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCourtRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourtRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *UpdateCourtRequest) GetCourtNo() int32 {
	if x != nil {
		return x.CourtNo
	}
	return 0
}

func (x *UpdateCourtRequest) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *UpdateCourtRequest) GetOpenFrom() string {
	if x != nil {
		return x.OpenFrom
	}
	return ""
}

func (x *UpdateCourtRequest) GetOpenTo() string {
	if x != nil {
		return x.OpenTo
	}
	return ""
}

type UpdateCourtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Court         *Court                 `protobuf:"bytes,1,opt,name=court,proto3" json:"court,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourtResponse) Reset() {
	*x = UpdateCourtResponse{}
	mi := &file_court_v1_court_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourtResponse) ProtoMessage() {}

func (x *UpdateCourtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourtResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourtResponse) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCourtResponse) GetCourt() *Court {
	if x != nil {
		return x.Court
	}
	return nil
}

type DeleteCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourtRequest) Reset() {
	*x = DeleteCourtRequest{}
	mi := &file_court_v1_court_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourtRequest) ProtoMessage() {}

func (x *DeleteCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourtRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourtRequest) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCourtRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourtResponse) Reset() {
	*x = DeleteCourtResponse{}
	mi := &file_court_v1_court_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourtResponse) ProtoMessage() {}

func (x *DeleteCourtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_court_v1_court_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourtResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourtResponse) Descriptor() ([]byte, []int) {
	return file_court_v1_court_proto_rawDescGZIP(), []int{10}
}

var File_court_v1_court_proto protoreflect.FileDescriptor

const file_court_v1_court_proto_rawDesc = "" +
	"\n" +
	"\x14court/v1/court.proto\x12\bcourt.v1\"\xbf\x01\n" +
	"\x05Court\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05venue\x18\x02 \x01(\tR\x05venue\x12\x19\n" +
	"\bcourt_no\x18\x03 \x01(\x05R\acourtNo\x12$\n" +
	"\x0eprice_per_hour\x18\x04 \x01(\x03R\fpricePerHour\x12\x1b\n" +
	"\topen_from\x18\x05 \x01(\tR\bopenFrom\x12\x17\n" +
	"\aopen_to\x18\x06 \x01(\tR\x06openTo\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\"\xa1\x01\n" +
	"\x12CreateCourtRequest\x12\x14\n" +
	"\x05venue\x18\x01 \x01(\tR\x05venue\x12\x19\n" +
	"\bcourt_no\x18\x02 \x01(\x05R\acourtNo\x12$\n" +
	"\x0eprice_per_hour\x18\x03 \x01(\x03R\fpricePerHour\x12\x1b\n" +
	"\topen_from\x18\x04 \x01(\tR\bopenFrom\x12\x17\n" +
	"\aopen_to\x18\x05 \x01(\tR\x06openTo\"<\n" +
	"\x13CreateCourtResponse\x12%\n" +
	"\x05court\x18\x01 \x01(\v2\x0f.court.v1.CourtR\x05court\"!\n" +
	"\x0fGetCourtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetCourtResponse\x12%\n" +
	"\x05court\x18\x01 \x01(\v2\x0f.court.v1.CourtR\x05court\"e\n" +
	"\x11ListCourtsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vvenue_query\x18\x03 \x01(\tR\n" +
	"venueQuery\"=\n" +
	"\x12ListCourtsResponse\x12'\n" +
	"\x06courts\x18\x01 \x03(\v2\x0f.court.v1.CourtR\x06courts\"\xb1\x01\n" +
	"\x12UpdateCourtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05venue\x18\x02 \x01(\tR\x05venue\x12\x19\n" +
	"\bcourt_no\x18\x03 \x01(\x05R\acourtNo\x12$\n" +
	"\x0eprice_per_hour\x18\x04 \x01(\x03R\fpricePerHour\x12\x1b\n" +
	"\topen_from\x18\x05 \x01(\tR\bopenFrom\x12\x17\n" +
	"\aopen_to\x18\x06 \x01(\tR\x06openTo\"<\n" +
	"\x13UpdateCourtResponse\x12%\n" +
	"\x05court\x18\x01 \x01(\v2\x0f.court.v1.CourtR\x05court\"$\n" +
	"\x12DeleteCourtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteCourtResponse2\xfe\x02\n" +
	"\fCourtService\x12J\n" +
	"\vCreateCourt\x12\x1c.court.v1.CreateCourtRequest\x1a\x1d.court.v1.CreateCourtResponse\x12A\n" +
	"\bGetCourt\x12\x19.court.v1.GetCourtRequest\x1a\x1a.court.v1.GetCourtResponse\x12G\n" +
	"\n" +
	"ListCourts\x12\x1b.court.v1.ListCourtsRequest\x1a\x1c.court.v1.ListCourtsResponse\x12J\n" +
	"\vUpdateCourt\x12\x1c.court.v1.UpdateCourtRequest\x1a\x1d.court.v1.UpdateCourtResponse\x12J\n" +
	"\vDeleteCourt\x12\x1c.court.v1.DeleteCourtRequest\x1a\x1d.court.v1.DeleteCourtResponseB9Z7github.com/you/badminton-booking/proto/court/v1;courtv1b\x06proto3"

var (
	file_court_v1_court_proto_rawDescOnce sync.Once
	file_court_v1_court_proto_rawDescData []byte
)

func file_court_v1_court_proto_rawDescGZIP() []byte {
	file_court_v1_court_proto_rawDescOnce.Do(func() {
		file_court_v1_court_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_court_v1_court_proto_rawDesc), len(file_court_v1_court_proto_rawDesc)))
	})
	return file_court_v1_court_proto_rawDescData
}

var file_court_v1_court_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_court_v1_court_proto_goTypes = []any{
	(*Court)(nil),               // 0: court.v1.Court
	(*CreateCourtRequest)(nil),  // 1: court.v1.CreateCourtRequest
	(*CreateCourtResponse)(nil), // 2: court.v1.CreateCourtResponse
	(*GetCourtRequest)(nil),     // 3: court.v1.GetCourtRequest
	(*GetCourtResponse)(nil),    // 4: court.v1.GetCourtResponse
	(*ListCourtsRequest)(nil),   // 5: court.v1.ListCourtsRequest
	(*ListCourtsResponse)(nil),  // 6: court.v1.ListCourtsResponse
	(*UpdateCourtRequest)(nil),  // 7: court.v1.UpdateCourtRequest
	(*UpdateCourtResponse)(nil), // 8: court.v1.UpdateCourtResponse
	(*DeleteCourtRequest)(nil),  // 9: court.v1.DeleteCourtRequest
	(*DeleteCourtResponse)(nil), // 10: court.v1.DeleteCourtResponse
}
var file_court_v1_court_proto_depIdxs = []int32{
	0,  // 0: court.v1.CreateCourtResponse.court:type_name -> court.v1.Court
	0,  // 1: court.v1.GetCourtResponse.court:type_name -> court.v1.Court
	0,  // 2: court.v1.ListCourtsResponse.courts:type_name -> court.v1.Court
	0,  // 3: court.v1.UpdateCourtResponse.court:type_name -> court.v1.Court
	1,  // 4: court.v1.CourtService.CreateCourt:input_type -> court.v1.CreateCourtRequest
	3,  // 5: court.v1.CourtService.GetCourt:input_type -> court.v1.GetCourtRequest
	5,  // 6: court.v1.CourtService.ListCourts:input_type -> court.v1.ListCourtsRequest
	7,  // 7: court.v1.CourtService.UpdateCourt:input_type -> court.v1.UpdateCourtRequest
	9,  // 8: court.v1.CourtService.DeleteCourt:input_type -> court.v1.DeleteCourtRequest
	2,  // 9: court.v1.CourtService.CreateCourt:output_type -> court.v1.CreateCourtResponse
	4,  // 10: court.v1.CourtService.GetCourt:output_type -> court.v1.GetCourtResponse
	6,  // 11: court.v1.CourtService.ListCourts:output_type -> court.v1.ListCourtsResponse
	8,  // 12: court.v1.CourtService.UpdateCourt:output_type -> court.v1.UpdateCourtResponse
	10, // 13: court.v1.CourtService.DeleteCourt:output_type -> court.v1.DeleteCourtResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_court_v1_court_proto_init() }
func file_court_v1_court_proto_init() {
	if File_court_v1_court_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_court_v1_court_proto_rawDesc), len(file_court_v1_court_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_court_v1_court_proto_goTypes,
		DependencyIndexes: file_court_v1_court_proto_depIdxs,
		MessageInfos:      file_court_v1_court_proto_msgTypes,
	}.Build()
	File_court_v1_court_proto = out.File
	file_court_v1_court_proto_goTypes = nil
	file_court_v1_court_proto_depIdxs = nil
}
